# Generated by Django 2.2.9 on 2020-01-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_assignmentteacherside_duedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentteacherside',
            name='maxPoint',
            field=models.IntegerField(default=100),
        ),
    ]
