# Generated by Django 2.2.9 on 2020-01-28 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_auto_20200128_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentteacherside',
            name='dueDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='assignmentteacherside',
            name='instructions',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='assignmentteacherside',
            name='maxPoint',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='assignmentteacherside',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
