# Generated by Django 2.2.9 on 2020-01-28 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_auto_20200128_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentteacherside',
            name='dueDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='assignmentteacherside',
            name='instructions',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='assignmentteacherside',
            name='maxPoint',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='assignmentteacherside',
            name='teacherUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignmentteacherside',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
