# Generated by Django 2.2.9 on 2020-01-30 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0009_studentassignments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='studentAssignments',
        ),
    ]
