# Generated by Django 2.2.9 on 2020-02-03 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0011_studentassignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentteacherside',
            name='teacherDocument',
            field=models.FileField(default='', upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='assignmentteacherside',
            name='videoLink',
            field=models.CharField(default='', max_length=80),
        ),
    ]
