# Generated by Django 2.2.9 on 2020-02-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0012_auto_20200202_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassignments',
            name='isSubmitted',
            field=models.BooleanField(default=False),
        ),
    ]
