# Generated by Django 2.2.9 on 2020-02-05 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0013_studentassignments_issubmitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentassignments',
            name='isSubmitted',
        ),
    ]
