# Generated by Django 2.2.9 on 2020-03-14 02:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0014_remove_studentassignments_issubmitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentteacherside',
            name='section',
            field=models.CharField(default=django.utils.timezone.now, max_length=25),
            preserve_default=False,
        ),
    ]
