# Generated by Django 2.2.9 on 2020-03-16 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0016_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='sections',
            name='description',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
    ]
