# Generated by Django 2.2.9 on 2020-03-17 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0018_auto_20200316_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentteacherside',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='assignments.Sections'),
        ),
    ]
