# Generated by Django 2.2.9 on 2020-03-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0021_auto_20200316_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='sections',
            name='public',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
