# Generated by Django 2.2.8 on 2020-03-23 22:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0022_sections_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentteacherside',
            name='startDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
