# Generated by Django 2.2.8 on 2020-03-23 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assignments', '0023_assignmentteacherside_startdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('instructions', models.TextField()),
                ('isSubmitted', models.BooleanField()),
                ('dueDate', models.DateTimeField()),
                ('teacherDocument', models.FileField(default='', upload_to='documents/')),
                ('videoLink', models.CharField(default='', max_length=80)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.Sections')),
                ('teacherUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
